
    create table address (
       id bigint generated by default as identity,
        city varchar(255),
        landmark varchar(255),
        state varchar(255),
        street varchar(255),
        zip integer,
        primary key (id)
    )

    create table patient (
       id bigint generated by default as identity,
        dob varchar(255),
        name varchar(255),
        national_id integer,
        phone_number varchar(255),
        address_id bigint,
        primary key (id)
    )

    create table pmh (
       id bigint generated by default as identity,
        charges double,
        creation_date DATE,
        description varchar(255),
        discharge_date DATE,
        hospital_admission boolean,
        is_alive boolean,
        name varchar(255),
        patient_id bigint,
        primary key (id)
    )

    alter table patient 
       add constraint FKlpwpmtdbdvnxm8fxlxpq2fugh 
       foreign key (address_id) 
       references address

    alter table pmh 
       add constraint FK7rgu5of1tlout3tivj7qowr30 
       foreign key (patient_id) 
       references patient

    create table address (
       id bigint generated by default as identity,
        city varchar(255),
        landmark varchar(255),
        state varchar(255),
        street varchar(255),
        zip integer,
        primary key (id)
    )

    create table patient (
       id bigint generated by default as identity,
        dob varchar(255),
        name varchar(255),
        national_id integer,
        phone_number varchar(255),
        address_id bigint,
        primary key (id)
    )

    create table pmh (
       id bigint generated by default as identity,
        charges double,
        creation_date DATE,
        description varchar(255),
        discharge_date DATE,
        hospital_admission boolean,
        is_alive boolean,
        name varchar(255),
        patient_id bigint,
        primary key (id)
    )

    alter table patient 
       add constraint FKlpwpmtdbdvnxm8fxlxpq2fugh 
       foreign key (address_id) 
       references address

    alter table pmh 
       add constraint FK7rgu5of1tlout3tivj7qowr30 
       foreign key (patient_id) 
       references patient

    create table address (
       id bigint generated by default as identity,
        city varchar(255),
        landmark varchar(255),
        state varchar(255),
        street varchar(255),
        zip integer,
        primary key (id)
    )

    create table patient (
       id bigint generated by default as identity,
        dob varchar(255),
        name varchar(255),
        national_id integer,
        phone_number varchar(255),
        address_id bigint,
        primary key (id)
    )

    create table pmh (
       id bigint generated by default as identity,
        charges double,
        creation_date DATE,
        description varchar(255),
        discharge_date DATE,
        hospital_admission boolean,
        is_alive boolean,
        name varchar(255),
        patient_id bigint,
        primary key (id)
    )

    alter table patient 
       add constraint FKlpwpmtdbdvnxm8fxlxpq2fugh 
       foreign key (address_id) 
       references address

    alter table pmh 
       add constraint FK7rgu5of1tlout3tivj7qowr30 
       foreign key (patient_id) 
       references patient

    create table address (
       id bigint generated by default as identity,
        city varchar(255),
        landmark varchar(255),
        state varchar(255),
        street varchar(255),
        zip integer,
        primary key (id)
    )

    create table patient (
       id bigint generated by default as identity,
        dob varchar(255),
        name varchar(255),
        national_id integer,
        phone_number varchar(255),
        address_id bigint,
        primary key (id)
    )

    create table pmh (
       id bigint generated by default as identity,
        charges double,
        creation_date DATE,
        description varchar(255),
        discharge_date DATE,
        hospital_admission boolean,
        is_alive boolean,
        name varchar(255),
        patient_id bigint,
        primary key (id)
    )

    alter table patient 
       add constraint FKlpwpmtdbdvnxm8fxlxpq2fugh 
       foreign key (address_id) 
       references address

    alter table pmh 
       add constraint FK7rgu5of1tlout3tivj7qowr30 
       foreign key (patient_id) 
       references patient

    create table address (
       id bigint generated by default as identity,
        city varchar(255),
        landmark varchar(255),
        state varchar(255),
        street varchar(255),
        zip integer,
        primary key (id)
    )

    create table patient (
       id bigint generated by default as identity,
        dob varchar(255),
        name varchar(255),
        national_id integer,
        phone_number varchar(255),
        address_id bigint,
        primary key (id)
    )

    create table pmh (
       id bigint generated by default as identity,
        charges double,
        creation_date DATE,
        description varchar(255),
        discharge_date DATE,
        hospital_admission boolean,
        is_alive boolean,
        name varchar(255),
        patient_id bigint,
        primary key (id)
    )

    alter table patient 
       add constraint FKlpwpmtdbdvnxm8fxlxpq2fugh 
       foreign key (address_id) 
       references address

    alter table pmh 
       add constraint FK7rgu5of1tlout3tivj7qowr30 
       foreign key (patient_id) 
       references patient
